name: test

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew linuxX64Test
      - run: ./gradlew linuxX86Test
      - run: make
      - run: prefix=usr make install
      - run: g++ src/nativeTest/cpp/test.cpp -I usr/include -L usr/lib -l decsync -pthread -o test
      - run: LD_LIBRARY_PATH=usr/lib ./test
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: CALL gradlew.bat mingwX64Test
        shell: cmd
      - run: CALL gradlew.bat mingwX86Test
        shell: cmd
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew macosX64Test
      - run: ./gradlew macosArm64Test